# Generated by Django 4.2.4 on 2023-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_social_links_userprofile_social_link_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
