# Generated by Django 4.2.4 on 2023-09-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='social_link_three',
            new_name='website_link',
        ),
    ]
