# Generated by Django 4.2.4 on 2023-12-13 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=32)),
                ('website_link', models.URLField(blank=True)),
                ('social_link_one', models.URLField(blank=True)),
                ('social_link_two', models.URLField(blank=True)),
                ('social_link_three', models.URLField(blank=True)),
                ('profile_picture', models.URLField(blank=True)),
                ('pronouns', models.CharField(blank=True, choices=[('they/them', 'They/Them'), ('she/her', 'She/Her'), ('he/him', 'He/Him')], max_length=10)),
                ('bio', models.TextField(blank=True, max_length=513)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('interests', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
