CATEGORIES = {
    "technology": "Technology",
    "music": "Music",
    "health and wellness": "Health and Wellness",
    "entertainment": "Entertainment",
    "travel and tourism": "Travel and Tourism",
    "education": "Education",
    "news": "News",
    "hobbies": "Hobbies",
    "food and nutrition": "Food and Nutrition",
    "personal finance": "Personal Finance",
    "sports": "Sports",
    "fashion and beauty": "Fashion and Beauty",
    "politics and government": "Politics and Government",
    "art and culture": "Art and Culture",
    "lifestyle": "Lifestyle",
    "environment": "Environment",
    "home and gardening": "Home and Gardening",
    "business and entrepreneurship": "Business and Entrepreneurship",
    "personal relationships": "Personal Relationships",
    "movies and television": "Movies and Television",
    "literature": "Literature",
    "history": "History",
    "religion": "Religion",
    "social networks": "Social Networks",
    "animals and pets": "Animals and Pets",
    "psychology": "Psychology",
    "photography": "Photography",
}
