// Icons.
import {
  FaBook,
  FaCamera,
  FaClock,
  FaCode,
  FaCoins,
  FaDumbbell,
  FaGlobe,
  FaGraduationCap,
  FaHandshakeSimple,
  FaHeart,
  FaLandmark,
  FaMicrochip,
  FaMusic,
  FaNewspaper,
  FaPalette,
  FaPaw,
  FaPlane,
  FaPlantWilt,
  FaScroll,
  FaSeedling,
  FaShield,
  FaShirt,
  FaTicket,
  FaUtensils,
  FaVolleyball,
} from "react-icons/fa6";

const categoryIcons = {
  technology: <FaMicrochip />,
  music: <FaMusic />,
  "art and culture": <FaPalette />,
  programming: <FaCode />,
  "animals and pets": <FaPaw />,
  education: <FaGraduationCap />,
  hobbies: <FaClock />,
  "social networks": <FaGlobe />,
  news: <FaNewspaper />,
  "food and nutrition": <FaUtensils />,
  "personal finance": <FaCoins />,
  "fashion and beauty": <FaShirt />,
  "politics and government": <FaLandmark />,
  lifestyle: <FaDumbbell />,
  sports: <FaVolleyball />,
  "health and wellness": <FaHeart />,
  environment: <FaSeedling />,
  "travel and tourism": <FaPlane />,
  cybersecurity: <FaShield />,
  relationships: <FaHandshakeSimple />,
  movies: <FaTicket />,
  history: <FaScroll />,
  literature: <FaBook />,
  "home and gardening": <FaPlantWilt />,
  photography: <FaCamera />,
};

export default categoryIcons;
