# Generated by Django 4.2.4 on 2023-12-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(max_length=32),
        ),
    ]
