# Generated by Django 4.2.4 on 2023-12-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsAPI', '0002_alter_userprofile_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_name',
            new_name='name',
        ),
    ]
